testlib=[{'id':'1',
          'productname':'Rubikscube',
          'article_number':123.123,
          'manifacturer':'Rubics',
          'price':69.69,
          'available_units':99,
          'description':'it\'s a toy',
          'shipment_size':'14x8x6',
          'image':'r1.png',   #link naar img? of kan img in lib?
          },
         {'id': '2',
          'productname': 'MagicCube',
          'article_number': 123.124,
          'manifacturer': 'Rubics',
          'price': 10.00,
          'available_units': 1,
          'description': 'it\'s a toy',
          'shipment_size': '14x8x6',
          'image':'r2.png',
          },
         {'id': '3',
          'productname': 'MagicCube',
          'article_number': 123.124,
          'manifacturer': 'Rubics',
          'price': 10.00,
          'available_units': 1,
          'description': 'it\'s a toy',
          'shipment_size': '14x8x6',
          'image':'r3.png',
          },
         {'id': '4',
          'productname': 'MagicCube',
          'article_number': 123.124,
          'manifacturer': 'Rubics',
          'price': 10.00,
          'available_units': 1,
          'description': 'it\'s a toy',
          'shipment_size': '14x8x6',
          'image':'r4.png',
          },
         {'id': '5',
          'productname': 'MagicCube',
          'article_number': 123.124,
          'manifacturer': 'Rubics',
          'price': 10.00,
          'available_units': 1,
          'description': 'it\'s a toy',
          'shipment_size': '14x8x6',
          'image':'r1.png',
          },
         {'id': '6',
          'productname': 'MagicCube',
          'article_number': 123.124,
          'manifacturer': 'Rubics',
          'price': 10.00,
          'available_units': 1,
          'description': 'it\'s a toy',
          'shipment_size': '14x8x6',
          'image':'r3.png',
          },
         {'id': '7',
          'productname': 'MagicCube',
          'article_number': 123.124,
          'manifacturer': 'Rubics',
          'price': 10.00,
          'available_units': 1,
          'description': 'it\'s a toy',
          'shipment_size': '14x8x6',
          'image':'r2.png',
          },
         {'id': '8',
          'productname': 'MagicCube',
          'article_number': 123.124,
          'manifacturer': 'Rubics',
          'price': 10.00,
          'available_units': 1,
          'description': 'it\'s a toy',
          'shipment_size': '14x8x6',
          'image':'r1.png',
          },
         {'id': '9',
          'productname': 'MagicCube',
          'article_number': 123.124,
          'manifacturer': 'Rubics',
          'price': 10.00,
          'available_units': 1,
          'description': 'it\'s a toy',
          'shipment_size': '14x8x6',
          'image':'r4.png',
          },
         {'id': '10',
          'productname': 'MagicCube',
          'article_number': 123.124,
          'manifacturer': 'Rubics',
          'price': 10.00,
          'available_units': 1,
          'description': 'it\'s a toy',
          'shipment_size': '14x8x6',
          'image':'r3.png',
          },
         {'id': '11',
          'productname': 'MagicCube',
          'article_number': 123.124,
          'manifacturer': 'Rubics',
          'price': 10.00,
          'available_units': 1,
          'description': 'it\'s a toy',
          'shipment_size': '14x8x6',
          'image':'r2.png',
          }
         ]
