"""empty message

Revision ID: 636a17db1b7f
Revises: b4338774bcf1
Create Date: 2023-01-31 10:06:27.199511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636a17db1b7f'
down_revision = 'b4338774bcf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('mollie_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'mollie_id')
    # ### end Alembic commands ###
