"""empty message

Revision ID: 97cf0f9cfd31
Revises: 34ef1563f6e9
Create Date: 2023-01-12 16:19:21.837484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97cf0f9cfd31'
down_revision = '34ef1563f6e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'user_id')
    # ### end Alembic commands ###
