"""empty message

Revision ID: b4338774bcf1
Revises: 97cf0f9cfd31
Create Date: 2023-01-25 14:44:51.591589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4338774bcf1'
down_revision = '97cf0f9cfd31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_line', sa.Column('order_id', sa.Integer(), nullable=True))
    op.drop_constraint('order_line_cart_id_fkey', 'order_line', type_='foreignkey')
    op.create_foreign_key(None, 'order_line', 'orders', ['order_id'], ['id'])
    op.drop_column('order_line', 'cart_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_line', sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order_line', type_='foreignkey')
    op.create_foreign_key('order_line_cart_id_fkey', 'order_line', 'orders', ['cart_id'], ['id'])
    op.drop_column('order_line', 'order_id')
    # ### end Alembic commands ###
